
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - test/**/*.mocks.dart

  errors:
    invalid_annotation_target: ignore
    
linter:
  rules:
    constant_identifier_names: false